package main

import (
	"fmt"
	"io"
	"strings"

	moirai "github.com/october-dev/moirai"
)

type valueType string

const (
	boolValue   valueType = "bool"
	formatValue valueType = "format"
	fileValue   valueType = "file"
	opaqueValue valueType = "opaque"
)

type flagSpec struct {
	name      string
	valueType valueType
}
type commandSpec struct {
	name        string
	subcommands []commandSpec
	flags       []flagSpec
	positional  string
}

// Keep ordered: these slices are the completion source of truth. The AST test
// checks them against the CLI dispatch and flag declarations.
var completionCommands = []commandSpec{
	{name: "help"}, {name: "version"},
	{name: "formats", flags: []flagSpec{{"json", boolValue}}},
	{name: "inspect", positional: "file", flags: []flagSpec{{"from", formatValue}, {"json", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "convert", positional: "file", flags: []flagSpec{{"from", formatValue}, {"to", formatValue}, {"out", fileValue}, {"max-input-bytes", opaqueValue}}},
	{name: "list", flags: []flagSpec{{"format", formatValue}, {"json", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "show", positional: "sessionID", flags: []flagSpec{{"format", formatValue}, {"json", boolValue}, {"thinking", boolValue}, {"tools", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "search", positional: "query", flags: []flagSpec{{"format", formatValue}, {"limit", opaqueValue}, {"json", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "export", positional: "sessionID", flags: []flagSpec{{"format", formatValue}, {"out", fileValue}, {"max-input-bytes", opaqueValue}}},
	{name: "import", positional: "file", flags: []flagSpec{{"from", formatValue}, {"to", formatValue}, {"with", formatValue}, {"no-launch", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "continue", positional: "file-or-id", flags: []flagSpec{{"from", formatValue}, {"to", formatValue}, {"with", formatValue}, {"no-launch", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "delete", positional: "sessionID", flags: []flagSpec{{"format", formatValue}, {"yes", boolValue}, {"max-input-bytes", opaqueValue}}},
	{name: "archive", positional: "archive-subcommand", subcommands: []commandSpec{
		{name: "create", positional: "file", flags: []flagSpec{{"from", formatValue}, {"out", fileValue}, {"max-input-bytes", opaqueValue}}},
		{name: "verify", positional: "file", flags: []flagSpec{{"max-input-bytes", opaqueValue}}},
	}},
	{name: "completion", positional: "shell-enum"},
}
var completionShells = []string{"bash", "zsh", "fish"}

func (a app) completion(args []string) error {
	if len(args) != 1 {
		return fmt.Errorf("completion requires one shell: bash, zsh, or fish")
	}
	var generate func([]string) string
	switch args[0] {
	case "bash":
		generate = bashCompletion
	case "zsh":
		generate = zshCompletion
	case "fish":
		generate = fishCompletion
	default:
		return fmt.Errorf("unknown completion shell %q (choose bash, zsh, or fish)", args[0])
	}
	formats := make([]string, len(moirai.Formats))
	for i, format := range moirai.Formats {
		formats[i] = string(format)
	}
	_, err := io.WriteString(a.out, generate(formats))
	return err
}

func commandNames(commands []commandSpec) string {
	names := make([]string, len(commands))
	for i, command := range commands {
		names[i] = command.name
	}
	return strings.Join(names, " ")
}
func eachCommand(visit func(string, commandSpec)) {
	for _, command := range completionCommands {
		visit(command.name, command)
		for _, sub := range command.subcommands {
			visit(command.name+" "+sub.name, sub)
		}
	}
}
func shellQuote(s string) string { return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'" }

func bashCompletion(formats []string) string {
	var b strings.Builder
	b.WriteString(`# Generated by moirai completion bash. Regenerate after upgrading.
_moirai_flag_kind() {
    kind=''
    case "$context:$1" in
`)
	eachCommand(func(name string, c commandSpec) {
		for _, f := range c.flags {
			fmt.Fprintf(&b, "        %s) kind=%s ;;\n", shellQuote(name+":"+f.name), f.valueType)
		}
	})
	b.WriteString(`    esac
}
_moirai() {
    local cur="${COMP_WORDS[COMP_CWORD]}" context="${COMP_WORDS[1]}"
    local word name kind pending='' ended=0 prefix='' choices='' positional='' candidate i
    COMPREPLY=()
    if (( COMP_CWORD == 1 )); then
`)
	fmt.Fprintf(&b, "        choices=%s\n", shellQuote(commandNames(completionCommands)))
	b.WriteString(`    else
        # Bash may split '=' into its own COMP_WORDS token. Keep a pending
        # value through that token, and consume exactly one actual value.
        for ((i=2; i<COMP_CWORD; i++)); do
            word=${COMP_WORDS[i]}
            if [[ -n $pending ]]; then
                [[ $word == = ]] && continue
                pending=''
                continue
            fi
            (( ended )) && continue
            if [[ $word == -- ]]; then ended=1; continue; fi
            if [[ $word == -* && $word != - ]]; then
                name=${word%%=*}
                while [[ $name == -* ]]; do name=${name#-}; done
                _moirai_flag_kind "$name"
                if [[ -n $kind && $kind != bool && $word != *=* ]]; then pending=$kind; fi
                continue
            fi
            # Only archive's first bare argument can select a subcommand.
            if [[ $context == archive ]]; then context="archive $word"; fi
        done
        if (( ! ended )); then
            if [[ -n $pending ]]; then
                [[ $cur == = ]] && cur=''
            elif [[ $cur == -*=* ]]; then
                name=${cur%%=*}
                prefix="$name="
                while [[ $name == -* ]]; do name=${name#-}; done
                _moirai_flag_kind "$name"
                pending=${kind:-opaque}
                cur=${cur#*=}
            fi
            if [[ -n $pending ]]; then
                case $pending in
`)
	fmt.Fprintf(&b, "                    format) choices=%s ;;\n", shellQuote(strings.Join(formats, " ")))
	b.WriteString(`                    file) positional=file ;;
                    *) return ;;
                esac
            else
                case $context in
`)
	eachCommand(func(name string, c commandSpec) {
		var flags []string
		for _, f := range c.flags {
			flags = append(flags, "--"+f.name)
		}
		choices := strings.Join(flags, " ")
		if len(c.subcommands) > 0 {
			choices = commandNames(c.subcommands)
		}
		if c.positional == "shell-enum" {
			choices = strings.Join(completionShells, " ")
		}
		fmt.Fprintf(&b, "                    %s) choices=%s; positional=%s ;;\n", shellQuote(name), shellQuote(choices), shellQuote(c.positional))
	})
	b.WriteString(`                esac
            fi
        else
            case $context in
`)
	eachCommand(func(name string, c commandSpec) {
		if c.positional == "file" || c.positional == "file-or-id" {
			fmt.Fprintf(&b, "                %s) positional=file ;;\n", shellQuote(name))
		}
	})
	b.WriteString(`            esac
        fi
    fi
    if [[ -n $choices ]]; then
        while IFS= read -r candidate; do
            COMPREPLY+=("$prefix$candidate")
        done < <(compgen -W "$choices" -- "$cur")
    fi
    if [[ $positional == file || $positional == file-or-id ]]; then
        if (( ended )) || [[ -n $pending || $cur != -* ]]; then
            while IFS= read -r candidate; do
                COMPREPLY+=("$prefix$candidate")
            done < <(compgen -f -- "$cur")
            compopt -o filenames 2>/dev/null || :
        fi
    fi
}
complete -F _moirai moirai
`)
	return b.String()
}

func zshCompletion(formats []string) string {
	var b strings.Builder
	b.WriteString(`#compdef moirai
# Generated by moirai completion zsh. Regenerate after upgrading.
_moirai() {
    local context state state_descr line
    local -A opt_args
    if (( CURRENT == 2 )); then
`)
	fmt.Fprintf(&b, "        _arguments '1:command:(%s)'\n        return\n    fi\n", commandNames(completionCommands))
	b.WriteString(`    context=$words[2]
    words=( "${words[@]:1}" )
    (( CURRENT-- ))
    if [[ $context == archive ]]; then
        if (( CURRENT == 2 )); then
`)
	for _, c := range completionCommands {
		if c.name == "archive" {
			fmt.Fprintf(&b, "            _arguments '1:subcommand:(%s)'\n", commandNames(c.subcommands))
		}
	}
	b.WriteString(`            return
        fi
        context="archive $words[2]"
        words=( "${words[@]:1}" )
        (( CURRENT-- ))
    fi
    case $context in
`)
	eachCommand(func(name string, c commandSpec) {
		fmt.Fprintf(&b, "        %s)\n            _arguments -S \\\n", shellQuote(name))
		for _, f := range c.flags {
			suffix := ""
			switch f.valueType {
			case formatValue:
				suffix = "=:format:(" + strings.Join(formats, " ") + ")"
			case fileValue:
				suffix = "=:file:_files"
			case opaqueValue:
				suffix = "=:value: "
			}
			// '=' permits values in the same word or the following word.
			for _, dash := range []string{"--", "-"} {
				fmt.Fprintf(&b, "                %s \\\n", shellQuote(dash+f.name+suffix))
			}
		}
		positional := "*:argument: "
		switch c.positional {
		case "file", "file-or-id":
			positional = "*:file:_files"
		case "shell-enum":
			positional = "1:shell:(" + strings.Join(completionShells, " ") + ")"
		case "archive-subcommand":
			positional = "1:subcommand:(" + commandNames(c.subcommands) + ")"
		}
		fmt.Fprintf(&b, "                %s\n            ;;\n", shellQuote(positional))
	})
	b.WriteString("    esac\n}\n# Support both fpath autoloading and explicitly sourcing this script.\nif [[ $funcstack[1] == _moirai ]]; then\n    _moirai \"$@\"\nelse\n    compdef _moirai moirai\nfi\n")
	return b.String()
}

func fishCompletion(formats []string) string {
	var b strings.Builder
	b.WriteString(`# Generated by moirai completion fish. Regenerate after upgrading.
# Check the dispatched words, not arbitrary words that happen to name commands.
function __moirai_context
    set -l words (commandline -opc)
    if test (count $words) -lt 2
        test "$argv[1]" = root
        return
    end
    set -l context $words[2]
    if test "$context" = archive; and test (count $words) -ge 3
        set context "archive $words[3]"
    end
    test "$context" = "$argv[1]"
end
# Native option completion handles values; this scanner gates positional rules
# so a flag value or a terminator is never mistaken for a positional suggestion.
function __moirai_position
    set -l words (commandline -opc)
    set -l context $words[2]
    set -l start 3
    if test "$context" = archive; and test (count $words) -ge 3
        set context "archive $words[3]"
        set start 4
    end
    set -l pending 0
    set -l ended 0
    for word in $words[$start..-1]
        if test $pending = 1
            set pending 0
            continue
        end
        if test $ended = 1
            continue
        end
        if test "$word" = --
            set ended 1
            continue
        end
        switch "$context:$word"
`)
	eachCommand(func(name string, c commandSpec) {
		for _, f := range c.flags {
			if f.valueType != boolValue {
				fmt.Fprintf(&b, "            case %s %s\n                set pending 1\n", shellQuote(name+":--"+f.name), shellQuote(name+":-"+f.name))
			}
		}
	})
	b.WriteString(`        end
    end
    test $pending = 0; or return 1
    if test "$argv[1]" = options
        test $ended = 0
    end
end
complete -c moirai -f
`)
	fmt.Fprintf(&b, "complete -c moirai -n '__moirai_context root' -a %s\n", shellQuote(commandNames(completionCommands)))
	eachCommand(func(name string, c commandSpec) {
		root := strings.Fields(name)[0]
		condition := "__fish_seen_subcommand_from " + root + "; and __moirai_context " + shellQuote(name)
		for _, f := range c.flags {
			extra := ""
			switch f.valueType {
			case formatValue:
				extra = " -x -a " + shellQuote(strings.Join(formats, " "))
			case fileValue:
				extra = " -r -F"
			case opaqueValue:
				extra = " -x"
			}
			fmt.Fprintf(&b, "complete -c moirai -n %s -l %s -o %s%s\n", shellQuote(condition), f.name, f.name, extra)
		}
		switch c.positional {
		case "file", "file-or-id":
			fmt.Fprintf(&b, "complete -c moirai -n %s -F\n", shellQuote(condition+"; and __moirai_position"))
		case "shell-enum":
			fmt.Fprintf(&b, "complete -c moirai -n %s -a %s\n", shellQuote(condition+"; and __moirai_position options"), shellQuote(strings.Join(completionShells, " ")))
		case "archive-subcommand":
			fmt.Fprintf(&b, "complete -c moirai -n %s -a %s\n", shellQuote(condition+"; and __moirai_position options"), shellQuote(commandNames(c.subcommands)))
		}
	})
	return b.String()
}
